services:
  react-app:
    build: ./isitwet-app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-boot-app
    volumes:
      - /etc/certs/isitwet:/etc/certs/

  spring-boot-app:
    build: ./isitwet-backend
    ports:
      - "8080:8080"
